#!/bin/sh
set -e
package_name=packagekit-force-autoremove
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/lib/x86_64-linux-gnu/packagekit-backend/libpk_backend_aptcc.so"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/lib/x86_64-linux-gnu/packagekit-backend/libpk_backend_aptcc.so"
;;
esac
exit 0
